In [9]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

data = load_iris()
X = data['data']
y = data['target']

X1, X2, y1, y2 = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X1 = scaler.fit_transform(X1)
X2 = scaler.transform(X2)

LR = LogisticRegression()
LR.fit(X1, y1)

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X1, y1)

y_pred_log_reg = LR.predict(X2)
accuracy_lr = accuracy_score(y2, y_pred_log_reg)

y_pred_knn = knn.predict(X2)
accuracy_knn = accuracy_score(y2, y_pred_knn)

print("Accuracy of Logistic Regression:", accuracy_lr)
print("Accuracy of KNN:", accuracy_knn)
print("\nClassification Report for Logistic Regression:\n", classification_report(y2, y_pred_log_reg))
print("Classification Report for KNN:\n", classification_report(y2, y_pred_knn))

print("Confusion Matrix for Logistic Regression:\n", confusion_matrix(y_test, y_pred_log_reg))
print("Confusion Matrix for KNN:\n", confusion_matrix(y_test, y_pred_knn))

Accuracy of Logistic Regression: 1.0
Accuracy of KNN: 1.0

Classification Report for Logistic Regression:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Classification Report for KNN:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Confusion Matrix for Logistic Regression:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Confusion Matrix fo